name: Node CI
  
on:
  schedule:
  - cron:  '0 * * * *'

jobs:
  build:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: make
      run: |
        node -v
        npm -v
        npm install
        make
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CI: true
